env:
  es6: true
extends:
  - eslint:recommended
  - prettier
overrides: []
plugins:
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prettier/prettier: error
globals:
  ARGV: readonly
  Debugger: readonly
  GIRepositoryGType: readonly
  globalThis: readonly
  imports: readonly
  Intl: readonly
  log: readonly
  logError: readonly
  print: readonly
  printerr: readonly
  window: readonly
  TextEncoder: readonly
  TextDecoder: readonly
  console: readonly
  setTimeout: readonly
  setInterval: readonly
  clearTimeout: readonly
  clearInterval: readonly
